messages and wargame messages export
serge-web/serge-legacy pull request #30
Opened 2019-05-31 06:35 UTC by lilitkarapetyan

2019-05-31 08:41 UTC, IanMayo commented
thanks for this @lilitkarapetyan  - are you able to fix the CodeFactor issue reported above?

2019-05-31 08:45 UTC, IanMayo commented on client/src/api/consts.js
> +export const serverPath = 'http://localhost:8080/';
@lilitkarapetyan - since we're going to deploy this to Heroku, we need to use the _other_ set of constants here, please.

2019-05-31 08:47 UTC, IanMayo commented
@jcdiprose - here's @lilitkarapetyan's code to export the messages to Excel.  I've added a comment about correcting the target URL so we can deploy it to Heroku.

I'd appreciate you also reviewing the PR, please.

2019-05-31 09:13 UTC, nousernames2 requested changes
A few changes for consistency and code quality.

2019-05-31 09:13 UTC, nousernames2 commented on client/src/ActionsAndReducers/ExportItems/ExportItems_Reducer.js
> +      return [...state, action.payload.exportData];
always use `copyStateHelper` from `Helpers` so if state grows in future it doesn't great bugs due to mutation.

i.e. newState = copyState(state);

\serge\client\src\Helpers\copyStateHelper.js

2019-05-31 09:13 UTC, nousernames2 commented on client/src/ActionsAndReducers/ExportItems/ExportItems_ActionsCreators.js
> +  payload: { exportData: exportData }
no need for object in payload rather than `{ exportData: exportData }` .

i.e.
```
export const createExportItem = (exportData) => ({
  type: ActionConstant.CREATE_EXPORT_ITEM,
  payload: exportData,
});
```

2019-05-31 09:13 UTC, jcdiprose commented on client/src/Components/ExcelExport.jsx
> +import React from 'react'
Always use `;`.

2019-05-31 09:13 UTC, jcdiprose commented on client/src/Components/ExcelExport.jsx
> +const ExcelExport = ({ exp, index }) => {
Always use class based react component style 
`class ExcelExport extends Component {`

2019-05-31 09:13 UTC, jcdiprose commented on client/src/Store/Store.jsx
> +  exportItems: exportItems,
Assign properties of same name like `{ exportItems }` rather than `{ exportItems: exportItems }`

2019-05-31 09:13 UTC, jcdiprose commented on client/src/Views/ExportMessages.jsx
> +    this.createExportItem = this.createExportItem.bind(this);
instead of binding `this` in the constructor, use `this.createExportItem = () => {  }` fat arrow function declaration as has `this` context of encapsulating function / class.

2019-05-31 09:13 UTC, jcdiprose commented on client/src/Views/ExportMessages.jsx
> +    this.state = {
Remove empty state.

2019-05-31 09:41 UTC, jcdiprose commented
Found bug with one message in channel and one message in OutOfGame messages Channel, clicking export gives this error .. 

```
TypeError: Cannot convert undefined or null to object
C:\Users\User\Documents\_projects\Serge\lilitMessagesExport\serge\client\src\Views\ExportMessages.jsx:109:7

```

2019-05-31 10:37 UTC, jcdiprose commented on client/src/Views/ExportMessages.jsx
> +    for(let msgK = 0; msgK < messagesFiltered.length; msgK++) {
This logic is not very descriptive. Please use more descriptive variable names and add short commentry if neccessary.

2019-05-31 10:40 UTC, jcdiprose commented on client/src/Views/ExportMessages.jsx
> +    this.props.dispatch(createExportItem({
This is attempting to export the wrong information.

e.g.

The spreadsheet will have one tab per message type. - (chat, machinery failure etc.) can create from messages property property `details.messageType`

That tab will contain a header row, containing the fields for that message.  Then it’s one row per message.  There would also be a leading column with the channel that message was sent in.

Meaning the csv should contain all of the game messages sent during the wargame.

2019-05-31 11:51 UTC, IanMayo commented on client/src/Views/ExportMessages.jsx
> +
@lilitkarapetyan - this is a bit of a guess, but I've tried to fix the logic for messagesFiltered.  I've modified it so that it ignore non-message objects, then it checks it contains `details.messageType`, then it checks that against the type we're looking for:

```
    const messagesFiltered = messages.filter(msg => {
      if(msg.schema) {
        return msg.schema.title === type.title;
      }
      else {
        switch (type.title) {
          case "infoType":
            return false;
          case "Game":
            return false;
          default:
            return msg.details != null && msg.details.messageType === type.title;
        }
      }
    });
```

But, as I said in UpWork, I think there's an alternate approach.  I don't think you need to start from the database of message types.  I think you could work through the database of messages, and build up a list of messages of each type.  Then just loop through these, once message-type at a time, and produce a tab of data per message type.

2019-06-15 13:30 UTC, IanMayo commented
@lilitkarapetyan  - I'm having a play with lessons export, and really enjoying it :-)

I've got one more feature request, please. It would be really useful to have the "author" of the message - the person who wrote it.

Here's a message:
![image](https://user-images.githubusercontent.com/1108513/59552006-882d5d80-8f79-11e9-8ea4-838b4bb26a45.png)

So, I'd like "force" and "role" to be exported please?

From the above message we'd get a column titled `force` that would be `umpire` and a column titled `role` that would contain `Game Control`.

Thanks :-)

2019-06-15 13:33 UTC, IanMayo commented
Aah, @lilitkarapetyan - I've merged an updated `development` branch into here. That's because I've made a change in how the "Game Admin" messages (from the right-hand side of the UI) are stored in the database. They were missing the "message-type" field, so they didn't get exported. They will now :-)

2019-06-17 11:20 UTC, IanMayo commented
Hi @lilitkarapetyan  and @jcdiprose  - I'm going to merge this.

It's close to what we want, and I don't want to get conflicts.  We can make other changes in other PRs

2019-06-17 11:20 UTC, merged